version: '3.5'

services:
  backend:
    build: ./backend
    container_name: backend
    image: backend
    # volumes:
    #   - ./backend/srcs:/app
    ports:
      - "3000:3000"
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    image: frontend
    volumes:
      - ./frontend/srcs:/app
    ports:
      - "4000:4000"
    restart: always

  database:
    build: ./database
    container_name: database
    image: database
    volumes:
      - ./database/srcs:/app
    ports:
      - "5000:5000"
    restart: always