version: '3.5'

services:
  backend:
    build: ./backend
    container_name: backend
    image: backend
    networks:
      - ft_transcendence
    ports:
      - "3000-3001:3000-3001"
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    image: frontend
    networks:
      - ft_transcendence
    ports:
      - "4000:4000"
    restart: always


networks:
  ft_transcendence: